// src/lib/components/QuranVirtualList.svelte
<script lang="ts">
	import VirtualScroll from 'svelte-virtual-scroll-list';
	import type { RenderableItem, GlobalVerseKey, GlobalHighlightedWords } from '$lib/types';
	import Bismillah from './Bismillah.svelte';
	import SurahHeader from './SurahHeader.svelte';
	import VerseRow from './VerseRow.svelte';

	interface Props {
		items: RenderableItem[];
		currentVerseKey: GlobalVerseKey | null;
		highlightedWords: GlobalHighlightedWords;
	}

	let { items, currentVerseKey, highlightedWords }: Props = $props();

	let virtualScroll: VirtualScroll;

	export function scrollToIndex(index: number): void {
		if (virtualScroll) {
			virtualScroll.scrollToIndex(index);
		}
	}
</script>

<div class="virtual-container">
	<VirtualScroll
		bind:this={virtualScroll}
		data={items}
		key="index"
		keeps={30}
		estimateSize={100}
		let:data={item}
	>
		<div class="max-w-3xl mx-auto px-4 py-2">
			{#if item.type === 'surah-header' && item.surahData}
				<SurahHeader surah={item.surahData} />
			{:else if item.type === 'bismillah'}
				<Bismillah />
			{:else if item.type === 'verse' && item.verse && item.verseKey}
				<VerseRow
					verse={item.verse}
					verseKey={item.verseKey}
					surahNumber={item.surahNumber}
					isCurrentVerse={currentVerseKey === item.verseKey}
					highlightedWordIndices={highlightedWords[item.verseKey]}
				/>
			{/if}
		</div>
	</VirtualScroll>
</div>

<style>
	.virtual-container {
		height: 100%;
		width: 100%;
		overflow: hidden;
	}

	.virtual-container :global(.virtual-scroll-wrapper) {
		height: 100% !important;
		padding-top: 70px;
		padding-bottom: 90px;
	}
</style>

// src/components/QuranVirtualList.tsx
import { forwardRef, useImperativeHandle, useRef, useCallback } from 'react';
import { Virtuoso, type VirtuosoHandle, type Components } from 'react-virtuoso';
import type { RenderableItem, GlobalVerseKey, GlobalHighlightedWords } from '../types';
import { SurahHeader } from './SurahHeader';
import { Bismillah } from './Bismillah';
import { VerseRow } from './VerseRow';

export interface QuranVirtualListHandle {
  scrollToIndex: (index: number, behavior?: 'auto' | 'smooth') => void;
}

interface QuranVirtualListProps {
  items: RenderableItem[];
  currentVerseKey: GlobalVerseKey | null;
  highlightedWords: GlobalHighlightedWords;
}

// Custom List component - defined outside to prevent recreation on each render
const ListContainer = forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ style, children, ...props }, ref) => (
    <div
      ref={ref}
      style={style}
      className="max-w-3xl mx-auto px-4 py-20 space-y-4"
      {...props}
    >
      {children}
    </div>
  )
);
ListContainer.displayName = 'ListContainer';

const virtuosoComponents: Components = {
  List: ListContainer,
};

export const QuranVirtualList = forwardRef<QuranVirtualListHandle, QuranVirtualListProps>(
  function QuranVirtualList({ items, currentVerseKey, highlightedWords }, ref) {
    const virtuosoRef = useRef<VirtuosoHandle>(null);

    useImperativeHandle(ref, () => ({
      scrollToIndex: (index: number, behavior: 'auto' | 'smooth' = 'smooth') => {
        virtuosoRef.current?.scrollToIndex({
          index,
          align: 'center',
          behavior,
        });
      },
    }));

    const renderItem = useCallback(
      (index: number) => {
        const item = items[index];

        if (!item) {
          return null;
        }

        switch (item.type) {
          case 'surah-header':
            return item.surahData ? <SurahHeader surah={item.surahData} /> : null;

          case 'bismillah':
            return <Bismillah />;

          case 'verse':
            if (!item.verse || !item.verseKey) {
              return null;
            }
            return (
              <VerseRow
                verse={item.verse}
                verseKey={item.verseKey}
                surahNumber={item.surahNumber}
                isCurrentVerse={item.verseKey === currentVerseKey}
                highlightedWordIndices={highlightedWords[item.verseKey]}
              />
            );

          default:
            return null;
        }
      },
      [items, currentVerseKey, highlightedWords]
    );

    if (items.length === 0) {
      return null;
    }

    return (
      <Virtuoso
        ref={virtuosoRef}
        totalCount={items.length}
        itemContent={renderItem}
        style={{ height: '100%' }}
        overscan={200}
        components={virtuosoComponents}
      />
    );
  }
);
